INSERT INTO products (title, price)
VALUES ('Bread1', 40),
       ('Lemon', 7),
       ('Orange', 6),
       ('Potato', 3),
       ('Elite Cheese', 257),
       ('Beer', 8),
       ('Rum', 187),
       ('Coca-cola', 65),
       ('Chips', 14),
       ('Snack', 3),
       ('Chocolate', 11),
       ('Meat', 223),
       ('Chicken', 198),
       ('Tea', 145),
       ('Coffee', 154),
       ('Butter', 80);
